// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0UBHFckjHujbb40xZSn5Xm9Oye6b350o',
    appId: '1:741956228223:web:883172a4dc3d220628db4a',
    messagingSenderId: '741956228223',
    projectId: 'todo-classwork',
    authDomain: 'todo-classwork.firebaseapp.com',
    storageBucket: 'todo-classwork.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHHaux59YJgy6laQx74igBZ-L_a4Q328I',
    appId: '1:741956228223:android:89955e2b4b8f576f28db4a',
    messagingSenderId: '741956228223',
    projectId: 'todo-classwork',
    storageBucket: 'todo-classwork.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFHfALUd1EqLvEMtCH1id66uw7vQ5RWos',
    appId: '1:741956228223:ios:97030b62772443d628db4a',
    messagingSenderId: '741956228223',
    projectId: 'todo-classwork',
    storageBucket: 'todo-classwork.appspot.com',
    iosBundleId: 'com.example.todoClassWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFHfALUd1EqLvEMtCH1id66uw7vQ5RWos',
    appId: '1:741956228223:ios:4157bcd31e18f1b628db4a',
    messagingSenderId: '741956228223',
    projectId: 'todo-classwork',
    storageBucket: 'todo-classwork.appspot.com',
    iosBundleId: 'com.example.todoClassWork.RunnerTests',
  );
}
